# Site settings
title: The PoliHydra Project
description: >
  Hydrogen embrittlement FE Analysis tools.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.polihydra.org" # the base hostname & protocol for your site

# Build settings
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
markdown: kramdown
sass:
    style: compressed
    sass_dir: _sass

exclude:
  - README.md
